version: '3.7'
services:
    snipeit:
        build: ./snipe-it
        container_name: snipeit
        env_file:
            - .env
        volumes:
            - snipe-vol:/var/lib/snipeit
            - ./cert/fullchain.pem:/var/lib/snipeit/ssl/snipeit-ssl.crt
            - ./cert/privkey.pem:/var/lib/snipeit/ssl/snipeit-ssl.key
        restart: always
        ports:
            - 80:80
            - 443:443
        links:
            - snipe-mysql:mysql
    snipe-mysql:
        image: mysql:5.6
        container_name: snipe-mysql
        env_file:
            - .env
        volumes:
            - snipesql-vol:/var/lib/mysql
        restart: always
        ports: 
            - 3306:3306
            
volumes:
    snipe-vol:
    snipesql-vol:
